/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stickynotes;

import java.awt.Point;
import java.io.File;

/**
 *
 * @author pawan
 */
public class mainFrame extends javax.swing.JFrame {
    static int instances = 0;
    File file=null;
    Point initialClick;
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        System.out.println("stickynotes.mainFrame.<init>()");
        instances++;
        setUndecorated(true);
        initComponents();
        setVisible(true);
        System.err.println("instance "+instances+ " created");
    //    textArea.setBackground(Color.getColor("red"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeApp = new javax.swing.JButton();
        closeFrame = new javax.swing.JButton();
        addFrame = new javax.swing.JButton();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 195, 139));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        setForeground(new java.awt.Color(235, 190, 105));
        setMinimumSize(new java.awt.Dimension(300, 150));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        closeApp.setText("x");
        closeApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAppActionPerformed(evt);
            }
        });

        closeFrame.setText("-");
        closeFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFrameActionPerformed(evt);
            }
        });

        addFrame.setText("+");
        addFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFrameActionPerformed(evt);
            }
        });

        textArea.setBackground(new java.awt.Color(253, 205, 157));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        textArea.setForeground(new java.awt.Color(240, 70, 114));
        textArea.setRows(5);
        textArea.setCaretColor(new java.awt.Color(225, 50, 50));
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAreaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textAreaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeApp))
            .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFrame)
                    .addComponent(closeFrame)
                    .addComponent(closeApp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_textAreaKeyTyped

    private void addFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFrameActionPerformed
        // TODO add your handling code here:
        mainFrame frame = new mainFrame();
        instances++;
    }//GEN-LAST:event_addFrameActionPerformed

    private void closeFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFrameActionPerformed
        // TODO add your handling code here:
        System.out.println("stickynotes.mainFrame.closeFrameActionPerformed()");
        if(file!=null)
           System.err.println("\tfile deleted "+file.getName());
        file.delete();
        if(instances ==1 )System.exit(0);
        else dispose();
        instances--;
    }//GEN-LAST:event_closeFrameActionPerformed

    private void closeAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAppActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeAppActionPerformed

    private void textAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyReleased
        // TODO add your handling code here:
        Saver S = new Saver();
       if(file==null)
           file = S.save(this);
       else
        S.save(file, this);
    }//GEN-LAST:event_textAreaKeyReleased

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int xMoved = this.getLocation().x+evt.getX() - initialClick.x;
        int yMoved = this.getLocation().y+evt.getY() - initialClick.y;
        this.setLocation(xMoved,yMoved);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFrame;
    private javax.swing.JButton closeApp;
    private javax.swing.JButton closeFrame;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    File getFilename()
    {   return file;}
    void setFilename(File filename)
    {   this.file = filename;    }
    
    String getTextArea() 
    {    return textArea.getText();   }

    void setTextArea(String textArea) 
    {   this.textArea.setText(textArea);}
}
